# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "CartesianPoint",
    "DistanceWeightedMetaModel",
    "FeedbackAggregator",
    "FeedbackEvent",
    "GeoPoint",
    "KernelPcaProjection",
    "LaplacianEigenmap",
    "NearestNeighborMetaModel",
    "PcaProjection",
    "Pipeline",
    "ProjectedPoint",
    "RandomProjection",
    "SphericalPoint",
    "angular_distance",
    "append_to_default_store",
    "auto_tune",
    "cartesian_to_spherical",
    "chord_distance",
    "corpus_features",
    "geo_to_spherical",
    "great_circle_distance",
    "load_default_store",
    "spherical_to_cartesian",
    "spherical_to_geo",
]

@typing.final
class CartesianPoint:
    @property
    def x(self) -> builtins.float: ...
    @property
    def y(self) -> builtins.float: ...
    @property
    def z(self) -> builtins.float: ...
    def __new__(cls, x: builtins.float, y: builtins.float, z: builtins.float) -> CartesianPoint: ...
    def magnitude(self) -> builtins.float: ...
    def normalize(self) -> CartesianPoint: ...
    def to_spherical(self) -> SphericalPoint: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: CartesianPoint) -> builtins.bool: ...

@typing.final
class DistanceWeightedMetaModel:
    r"""
    Distance-weighted meta-model: picks the training record that
    maximizes `best_score × 1/(distance + epsilon)`, balancing similarity
    and observed quality.
    """
    @property
    def name(self) -> builtins.str: ...
    def __new__(cls, *, epsilon: builtins.float = 0.1) -> DistanceWeightedMetaModel: ...
    def fit(self, records: typing.Any) -> None: ...
    def predict(self, features: typing.Any) -> typing.Any: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FeedbackAggregator:
    r"""
    Accumulates [`FeedbackEvent`]s and summarizes them by `corpus_id`.
    """
    def __new__(cls) -> FeedbackAggregator: ...
    @staticmethod
    def load(path: builtins.str) -> FeedbackAggregator:
        r"""
        Load an aggregator from a JSON file, or return an empty one if
        the file does not exist.
        """
    @staticmethod
    def load_default() -> FeedbackAggregator:
        r"""
        Load the default store at `~/.sphereql/feedback_events.json`.
        """
    def save(self, path: builtins.str) -> None: ...
    def record(self, event: FeedbackEvent) -> None: ...
    def __len__(self) -> builtins.int: ...
    def __bool__(self) -> builtins.bool: ...
    def corpus_ids(self) -> builtins.list[builtins.str]: ...
    def summarize(self, corpus_id: builtins.str) -> typing.Optional[typing.Any]:
        r"""
        Summarize feedback for one corpus. Returns None if no events.
        """
    def summarize_all(self) -> typing.Any:
        r"""
        Summarize every corpus that has events.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FeedbackEvent:
    r"""
    One user-supplied satisfaction signal attached to a specific query.
    
    `score` is a scalar in `[0, 1]`; the aggregator clamps it at
    summarize time, so stored raw values are preserved.
    """
    @property
    def corpus_id(self) -> builtins.str: ...
    @property
    def query_id(self) -> builtins.str: ...
    @property
    def score(self) -> builtins.float: ...
    @property
    def timestamp(self) -> builtins.str: ...
    def __new__(cls, corpus_id: builtins.str, query_id: builtins.str, score: builtins.float, timestamp: typing.Optional[builtins.str] = None) -> FeedbackEvent: ...
    def to_dict(self) -> typing.Any: ...
    def append_to_default_store(self) -> builtins.str:
        r"""
        Append this event to `~/.sphereql/feedback_events.json`.
        Returns the absolute path of the store file.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GeoPoint:
    @property
    def lat(self) -> builtins.float: ...
    @property
    def lon(self) -> builtins.float: ...
    @property
    def alt(self) -> builtins.float: ...
    def __new__(cls, lat: builtins.float, lon: builtins.float, alt: builtins.float) -> GeoPoint: ...
    def to_spherical(self) -> SphericalPoint: ...
    def to_cartesian(self) -> CartesianPoint: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: GeoPoint) -> builtins.bool: ...

@typing.final
class KernelPcaProjection:
    @property
    def dimensionality(self) -> builtins.int: ...
    @property
    def explained_variance_ratio(self) -> builtins.float: ...
    @property
    def sigma(self) -> builtins.float: ...
    @property
    def num_training_points(self) -> builtins.int: ...
    @classmethod
    def fit(cls, embeddings: typing.Any, *, sigma: typing.Optional[builtins.float] = None, radial: typing.Optional[typing.Any] = None, volumetric: builtins.bool = False) -> KernelPcaProjection: ...
    def project(self, embedding: typing.Any) -> SphericalPoint: ...
    def project_rich(self, embedding: typing.Any) -> ProjectedPoint: ...
    def project_batch(self, embeddings: typing.Any) -> builtins.list[SphericalPoint]: ...
    def project_rich_batch(self, embeddings: typing.Any) -> builtins.list[ProjectedPoint]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LaplacianEigenmap:
    @property
    def dimensionality(self) -> builtins.int: ...
    @property
    def explained_variance_ratio(self) -> builtins.float:
        r"""
        Mean of `|μ_k|` across the three retained eigenvalues, in `[0, 1]`.
        Exposed under the same name as PCA's EVR for adaptive-threshold
        compatibility — but the two quantities have distinct meaning.
        """
    @property
    def connectivity_ratio(self) -> builtins.float:
        r"""
        Same scalar as `explained_variance_ratio`, but under the
        spectrally-accurate name.
        """
    @property
    def eigenvalues(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        The three retained non-trivial eigenvalues, in descending order.
        """
    @classmethod
    def fit(cls, embeddings: typing.Any, *, radial: typing.Optional[typing.Any] = None, k_neighbors: typing.Optional[builtins.int] = None, active_threshold: typing.Optional[builtins.float] = None) -> LaplacianEigenmap:
        r"""
        Fit a Laplacian-eigenmap projection to a corpus.
        
        - `embeddings`: 2-D numpy array (f32/f64) or list-of-lists; needs
          at least 4 rows and any positive dimensionality.
        - `radial`: `"magnitude"` (default) or a finite float to fix the
          radial coordinate.
        - `k_neighbors`: density of the sparsified k-NN graph. Higher =
          smoother embedding, less noise-sensitivity, but more blurred
          category boundaries. Typical range 10–30; defaults to 15.
        - `active_threshold`: absolute-weight cutoff for the active-axis
          filter. Axes with `|v| ≤ threshold` are dropped before computing
          Jaccard similarity. Defaults to 0.05.
        """
    def project(self, embedding: typing.Any) -> SphericalPoint: ...
    def project_rich(self, embedding: typing.Any) -> ProjectedPoint: ...
    def project_batch(self, embeddings: typing.Any) -> builtins.list[SphericalPoint]: ...
    def project_rich_batch(self, embeddings: typing.Any) -> builtins.list[ProjectedPoint]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class NearestNeighborMetaModel:
    r"""
    Nearest-neighbor meta-model: picks the training record whose corpus
    feature vector is closest to the query (z-score normalized Euclidean).
    """
    @property
    def name(self) -> builtins.str: ...
    def __new__(cls) -> NearestNeighborMetaModel: ...
    def fit(self, records: typing.Any) -> None:
        r"""
        Fit on a list of training records (dicts with `corpus_id`,
        `features`, `best_config`, `best_score`, `metric_name`,
        `strategy`, `timestamp`).
        """
    def predict(self, features: typing.Any) -> typing.Any:
        r"""
        Predict the PipelineConfig for a new corpus profile. Returns a
        dict ready to pass to `Pipeline(categories, embeddings, config=...)`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PcaProjection:
    @property
    def dimensionality(self) -> builtins.int: ...
    @property
    def explained_variance_ratio(self) -> builtins.float: ...
    @classmethod
    def fit(cls, embeddings: typing.Any, *, radial: typing.Optional[typing.Any] = None, volumetric: builtins.bool = False) -> PcaProjection: ...
    def project(self, embedding: typing.Any) -> SphericalPoint: ...
    def project_rich(self, embedding: typing.Any) -> ProjectedPoint: ...
    def project_batch(self, embeddings: typing.Any) -> builtins.list[SphericalPoint]: ...
    def project_rich_batch(self, embeddings: typing.Any) -> builtins.list[ProjectedPoint]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Pipeline:
    ...

@typing.final
class ProjectedPoint:
    @property
    def position(self) -> SphericalPoint: ...
    @property
    def certainty(self) -> builtins.float: ...
    @property
    def intensity(self) -> builtins.float: ...
    @property
    def projection_magnitude(self) -> builtins.float: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class RandomProjection:
    @property
    def dimensionality(self) -> builtins.int: ...
    def __new__(cls, dim: builtins.int, *, radial: typing.Optional[typing.Any] = None, seed: builtins.int = 42) -> RandomProjection: ...
    def project(self, embedding: typing.Any) -> SphericalPoint: ...
    def project_rich(self, embedding: typing.Any) -> ProjectedPoint: ...
    def project_batch(self, embeddings: typing.Any) -> builtins.list[SphericalPoint]: ...
    def project_rich_batch(self, embeddings: typing.Any) -> builtins.list[ProjectedPoint]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SphericalPoint:
    @property
    def r(self) -> builtins.float: ...
    @property
    def theta(self) -> builtins.float: ...
    @property
    def phi(self) -> builtins.float: ...
    def __new__(cls, r: builtins.float, theta: builtins.float, phi: builtins.float) -> SphericalPoint: ...
    def to_cartesian(self) -> CartesianPoint: ...
    def to_geo(self) -> GeoPoint: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: SphericalPoint) -> builtins.bool: ...

def angular_distance(a: SphericalPoint, b: SphericalPoint) -> builtins.float: ...

def append_to_default_store(record: typing.Any) -> builtins.str:
    r"""
    Append one training record to the default store. Returns the absolute
    path of the store file.
    """

def auto_tune(categories: typing.Sequence[builtins.str], embeddings: typing.Any, *, metric: builtins.str = 'default_composite', strategy: builtins.str = 'random', budget: builtins.int = 24, seed: builtins.int = 0, warmup: builtins.int = 4, gamma: builtins.float = 0.25, base_config: typing.Optional[typing.Any] = None, search_space: typing.Optional[typing.Any] = None) -> tuple[Pipeline, typing.Any]:
    r"""
    Run the auto-tuner over a default [`SearchSpace`] and return the
    best-scoring pipeline alongside a summary report.
    
    Args:
        categories: Category label per embedding.
        embeddings: List of embedding vectors.
        metric: Quality metric name. One of `territorial_health`,
            `bridge_coherence`, `cluster_silhouette`, `graph_modularity`,
            `default_composite`, `connectivity_composite`.
            Default: `default_composite`.
        strategy: One of `grid`, `random`, `bayesian`. Default: `random`.
        budget: Number of trials for `random` / `bayesian`. Default: 24.
        seed: RNG seed for `random` / `bayesian`. Default: 0.
        warmup: Warmup trials before acquisition kicks in (Bayesian only).
            Default: 4.
        gamma: Fraction of trials treated as "good" (Bayesian only).
            Default: 0.25.
        base_config: Optional dict of PipelineConfig. Non-tuned knobs
            stay at these values; tuned knobs explore the search space
            starting from them. Default: PipelineConfig.default().
        search_space: Optional dict of SearchSpace. Any field may be
            omitted — missing fields fall back to SearchSpace.default().
            Lists override the default candidate values for that knob.
    
    Returns:
        Tuple `(Pipeline, report)` where `report` is a dict with
        `metric_name`, `best_score`, `best_config`, `trials_count`,
        `failures_count`, `mean_score`.
    """

def cartesian_to_spherical(p: CartesianPoint) -> SphericalPoint: ...

def chord_distance(a: SphericalPoint, b: SphericalPoint) -> builtins.float: ...

def corpus_features(categories: typing.Sequence[builtins.str], embeddings: typing.Any) -> typing.Any:
    r"""
    Extract a corpus feature profile.
    
    Returns a dict matching [`CorpusFeatures`]'s serde representation:
    `n_items`, `n_categories`, `dim`, `mean_members_per_category`,
    `category_size_entropy`, `mean_sparsity`, `axis_utilization_entropy`,
    `noise_estimate`, `mean_intra_category_similarity`,
    `mean_inter_category_similarity`, `category_separation_ratio`.
    
    This is the input any [`MetaModel`] uses to predict a `PipelineConfig`
    for a previously-unseen corpus.
    
    Args:
        categories: Category label per embedding.
        embeddings: List of embedding vectors (list[list[float]] or np.ndarray).
    
    Returns:
        dict of corpus features.
    """

def geo_to_spherical(p: GeoPoint) -> SphericalPoint: ...

def great_circle_distance(a: SphericalPoint, b: SphericalPoint, radius: builtins.float) -> builtins.float: ...

def load_default_store() -> typing.Any:
    r"""
    Load all training records from the default store at
    `~/.sphereql/meta_records.json`. Returns an empty list if the
    store does not exist yet.
    """

def spherical_to_cartesian(p: SphericalPoint) -> CartesianPoint: ...

def spherical_to_geo(p: SphericalPoint) -> GeoPoint: ...

