"""
Gap-fill concept lists for SphereQL categories underrepresented in
OpenAlex's academic topic taxonomy.

Each entry is (label, keywords) where keywords are fed into the axis
mapper from mappings.py to generate sparse feature vectors.
"""

GAP_FILL_CONCEPTS: dict[str, list[tuple[str, list[str]]]] = {
    "culinary_arts": [
        ("Molecular gastronomy", ["chemistry", "cooking", "flavor", "texture", "emulsification"]),
        ("Bread fermentation science", ["fermentation", "yeast", "gluten", "baking", "chemistry"]),
        ("Flavor pairing theory", ["flavor", "aroma", "compound", "pairing", "taste"]),
        ("Maillard reaction chemistry", ["reaction", "browning", "amino acid", "cooking", "flavor"]),
        ("Sauce emulsion stability", ["emulsification", "chemistry", "cooking", "colloidal", "flavor"]),
        ("Sous vide precision cooking", ["temperature", "cooking", "precision", "measurement", "texture"]),
        ("Chocolate tempering science", ["crystal", "temperature", "cooking", "chemistry", "material"]),
        ("Fermented foods microbiology", ["fermentation", "bacteria", "culture", "cooking", "biology"]),
        ("Umami receptor biochemistry", ["taste", "receptor", "biochemistry", "neuroscience", "flavor"]),
        ("Sourdough starter dynamics", ["fermentation", "microbiology", "yeast", "bacteria", "baking"]),
        ("Espresso extraction physics", ["pressure", "thermal", "chemistry", "flavor", "kinetic"]),
        ("Coffee brewing chemistry", ["chemistry", "thermal", "aroma", "flavor", "molecular"]),
        ("Tea polyphenol chemistry", ["chemistry", "polymer", "biology", "flavor", "molecular"]),
        ("Wine fermentation kinetics", ["fermentation", "kinetic", "chemistry", "biology", "cuisine"]),
        ("Cheese aging microbiology", ["fermentation", "biology", "enzyme", "molecular", "culinary"]),
        ("Knife skills biomechanics", ["motion", "force", "performance", "cooking", "skill"]),
        ("Pastry lamination geometry", ["geometric", "structure", "baking", "pattern", "cooking"]),
        ("Dough rheology and elasticity", ["elasticity", "structure", "baking", "polymer", "measurement"]),
        ("Taste perception neuroscience", ["taste", "perception", "neural", "brain", "cognition"]),
        ("Olfactory memory and cuisine", ["aroma", "memory", "cognition", "cuisine", "perception"]),
        ("Salt curing thermodynamics", ["thermodynamic", "chemistry", "cooking", "preservation", "diffusion"]),
        ("Smoking and flavor compounds", ["smoke", "compound", "flavor", "aroma", "cooking"]),
        ("Dry aging beef enzymology", ["enzyme", "protein", "flavor", "biology", "cooking"]),
        ("Plating composition design", ["composition", "design", "visual", "culinary", "aesthetic"]),
        ("Spice trade history", ["spice", "trade", "history", "culture", "economy"]),
        ("Probiotics in fermented foods", ["fermentation", "biology", "health", "bacteria", "cooking"]),
        ("Honey crystallization chemistry", ["crystal", "chemistry", "molecular", "compound", "culinary"]),
        ("Caramelization kinetics", ["kinetic", "thermal", "chemistry", "reaction", "cooking"]),
        ("Bread crumb structure analysis", ["structure", "pattern", "baking", "texture", "measurement"]),
        ("Meat tenderization biochemistry", ["enzyme", "protein", "molecular", "cooking", "chemistry"]),
        ("Pickling acid chemistry", ["chemistry", "reaction", "preservation", "compound", "fermentation"]),
        ("Frying oil thermal stability", ["thermal", "lipid", "chemistry", "cooking", "frying"]),
        ("Egg coagulation chemistry", ["protein", "thermal", "chemistry", "cooking", "molecular"]),
        ("Custard texture rheology", ["texture", "structure", "cooking", "measurement", "molecular"]),
        ("Ice cream colloidal science", ["chemistry", "thermal", "molecular", "cooking", "structure"]),
        ("Sugar crystallization control", ["crystal", "chemistry", "molecular", "cooking", "thermal"]),
        ("Yogurt bacterial cultures", ["fermentation", "biology", "bacteria", "cooking", "culture"]),
        ("Kimchi fermentation pathways", ["fermentation", "biology", "tradition", "cuisine", "chemistry"]),
        ("Curry spice synergy", ["spice", "flavor", "aroma", "tradition", "cuisine"]),
        ("Sushi rice acidification", ["chemistry", "fermentation", "tradition", "cuisine", "cooking"]),
        ("Pasta extrusion geometry", ["geometric", "structure", "cooking", "pattern", "design"]),
        ("Risotto starch release", ["chemistry", "polymer", "cooking", "molecular", "cuisine"]),
        ("Mole sauce complexity", ["complex system", "flavor", "tradition", "cuisine", "cooking"]),
        ("Tagine slow-cooking thermodynamics", ["thermodynamic", "cooking", "tradition", "cuisine", "thermal"]),
        ("Tandoor heat dynamics", ["thermal", "tradition", "cooking", "cuisine", "heat transfer"]),
        ("Wok hei flavor chemistry", ["thermal", "flavor", "chemistry", "tradition", "cooking"]),
        ("Bouillabaisse infusion", ["infusion", "flavor", "tradition", "cuisine", "cooking"]),
        ("Charcuterie microbial safety", ["bacteria", "biology", "preservation", "cooking", "culinary"]),
        ("Restaurant kitchen workflow optimization", ["optimization", "system", "performance", "cooking", "behavior"]),
        ("Plant-based meat texture engineering", ["texture", "polymer", "protein", "cooking", "design"]),
        ("Cellular agriculture cell biology", ["cell", "biology", "molecular", "culinary", "engineering"]),
        ("Edible insect nutrition", ["protein", "biology", "culture", "nutrition", "cuisine"]),
        ("Slow food cultural movement", ["culture", "tradition", "cuisine", "society", "movement"]),
        ("Volatile aroma compounds analysis", ["aroma", "compound", "chemistry", "molecular", "measurement"]),
        ("Food allergen molecular biology", ["protein", "molecular", "biology", "immunology", "culinary"]),
        ("Texture analysis instrumentation", ["measurement", "texture", "sensor", "cooking", "structure"]),
    ],
    "architecture": [
        ("Gothic cathedral engineering", ["structure", "engineering", "historical", "stone", "design"]),
        ("Parametric facade design", ["design", "computation", "algorithm", "geometry", "surface"]),
        ("Biophilic design principles", ["nature", "design", "psychology", "well-being", "space"]),
        ("Seismic-resistant structures", ["earthquake", "structure", "force", "engineering", "material"]),
        ("Passive solar building design", ["energy", "solar", "thermal", "design", "sustainability"]),
        ("Acoustic design in concert halls", ["acoustics", "sound", "wave", "space", "design"]),
        ("Net-zero energy buildings", ["energy", "sustainability", "design", "systems", "measurement"]),
        ("BIM and digital twin modeling", ["computation", "data", "design", "systems", "software"]),
        ("Islamic geometric pattern design", ["geometry", "pattern", "culture", "design", "symmetry"]),
        ("Space syntax and pedestrian flow", ["network", "space", "behavior", "design", "measurement"]),
        ("Vernacular adobe construction", ["material", "tradition", "structure", "design", "culture"]),
        ("Tensile membrane structures", ["structure", "tension", "material", "design", "geometric"]),
        ("Geodesic dome geometry", ["geometric", "structure", "pattern", "design", "topology"]),
        ("Reinforced concrete history", ["material", "structure", "history", "engineering", "design"]),
        ("Earthquake retrofit engineering", ["earthquake", "structure", "engineering", "force", "design"]),
        ("Climate-adaptive vernacular design", ["climate", "tradition", "design", "thermal", "structure"]),
        ("Brutalism aesthetic theory", ["aesthetic", "theory", "design", "history", "material"]),
        ("Postmodern facade ornament", ["design", "history", "pattern", "structure", "visual"]),
        ("Daylighting analysis methods", ["light", "design", "measurement", "energy", "structure"]),
        ("Wind load engineering", ["force", "engineering", "structure", "fluid", "design"]),
        ("Computational form-finding", ["computation", "algorithm", "design", "geometric", "optimization"]),
        ("Bridge structural mechanics", ["structure", "force", "engineering", "design", "material"]),
        ("Skyscraper outrigger systems", ["structure", "engineering", "design", "force", "system"]),
        ("Zoning law and urban form", ["legal", "society", "design", "policy", "space"]),
        ("Transit-oriented development", ["transport", "design", "society", "policy", "system"]),
        ("Public space behavior studies", ["behavior", "space", "society", "design", "measurement"]),
        ("Affordable housing design", ["design", "society", "policy", "structure", "community"]),
        ("Cross-laminated timber buildings", ["material", "structure", "design", "engineering", "sustainability"]),
        ("Cradle-to-cradle materials", ["material", "sustainability", "design", "system", "life cycle"]),
        ("Heritage building conservation", ["heritage", "conservation", "history", "material", "design"]),
        ("Indigenous earth architecture", ["indigenous", "tradition", "material", "design", "structure"]),
        ("Bauhaus design philosophy", ["design", "history", "philosophy", "structure", "education"]),
        ("Le Corbusier modulor proportion", ["proportion", "design", "history", "geometric", "structure"]),
        ("Frank Lloyd Wright organic design", ["design", "nature", "history", "structure", "space"]),
        ("Japanese minka timber framing", ["tradition", "material", "structure", "design", "history"]),
        ("Roman aqueduct hydraulics", ["water", "structure", "engineering", "history", "ancient"]),
        ("Egyptian pyramid geometry", ["geometric", "structure", "ancient", "history", "design"]),
        ("Greek classical orders", ["history", "ancient", "design", "structure", "proportion"]),
        ("Byzantine dome construction", ["history", "structure", "design", "geometric", "ancient"]),
        ("Renaissance perspective architecture", ["history", "geometric", "design", "structure", "visual"]),
        ("Baroque spatial dramatics", ["history", "space", "design", "structure", "visual"]),
        ("Prefabricated modular housing", ["modular", "design", "manufactur", "structure", "system"]),
        ("Sustainable urban drainage", ["water", "sustainability", "system", "design", "ecological"]),
        ("Green roof ecosystem services", ["ecosystem", "design", "sustainability", "vegetation", "structure"]),
        ("Acoustic envelope design", ["acoustics", "design", "sound", "wave", "structure"]),
        ("Fire protection engineering", ["thermal", "engineering", "design", "safety", "material"]),
        ("Earthquake base isolation", ["earthquake", "structure", "force", "engineering", "design"]),
        ("Light wells and atria", ["light", "space", "design", "structure", "thermal"]),
        ("Curtain wall thermal performance", ["thermal", "performance", "design", "structure", "measurement"]),
        ("3D printed concrete construction", ["computation", "material", "manufactur", "design", "structure"]),
        ("Carbon-negative building materials", ["material", "sustainability", "chemistry", "design", "climate"]),
        ("Universal design accessibility", ["design", "behavior", "society", "rights", "structure"]),
        ("Smart building IoT systems", ["sensor", "data", "system", "design", "network"]),
        ("Healthcare facility planning", ["design", "behavior", "healthcare", "space", "system"]),
        ("Waterfront resilience design", ["water", "climate", "design", "structure", "ecological"]),
    ],
    "performing_arts": [
        ("Method acting psychology", ["psychology", "emotion", "behavior", "embodiment", "performance"]),
        ("Contact improvisation technique", ["movement", "dance", "improvisation", "body", "performance"]),
        ("Classical Indian dance forms", ["tradition", "culture", "rhythm", "narrative", "dance"]),
        ("Circus arts biomechanics", ["biomechanics", "motion", "force", "performance", "body"]),
        ("Ballet pointe technique biomechanics", ["biomechanics", "force", "anatomy", "dance", "performance"]),
        ("Stage lighting design", ["light", "design", "visual", "color", "performance"]),
        ("Voice training and projection", ["sound", "anatomy", "performance", "training", "resonance"]),
        ("Butoh dance philosophy", ["dance", "philosophy", "body", "expression", "performance"]),
        ("Audience reception psychology", ["psychology", "behavior", "cognition", "emotion", "performance"]),
        ("Motion capture for performance", ["motion", "technology", "data", "performance", "dance"]),
        ("Stanislavski emotional memory", ["emotion", "memory", "psychology", "acting", "performance"]),
        ("Brechtian alienation effect", ["theatr", "philosophy", "narrative", "audience", "performance"]),
        ("Greek chorus dramaturgy", ["theatr", "tradition", "history", "narrative", "performance"]),
        ("Kabuki theater tradition", ["theatr", "tradition", "culture", "performance", "history"]),
        ("Beijing opera makeup symbolism", ["culture", "tradition", "color", "symbol", "performance"]),
        ("Mime body language", ["motion", "behavior", "performance", "language", "communication"]),
        ("Stage combat choreography", ["choreograph", "motion", "performance", "stage", "training"]),
        ("Improv theater principles", ["improvis", "theatr", "performance", "behavior", "cognition"]),
        ("Chamber dance ensemble dynamics", ["dance", "ensemble", "motion", "performance", "rhythm"]),
        ("Hip-hop dance battle culture", ["dance", "culture", "rhythm", "performance", "movement"]),
        ("Capoeira martial dance", ["dance", "tradition", "motion", "culture", "performance"]),
        ("Whirling dervish meditation", ["meditation", "dance", "spiritual", "tradition", "motion"]),
        ("Aerial silks performance", ["motion", "performance", "force", "training", "dance"]),
        ("Slam poetry performance", ["poetry", "performance", "rhythm", "narrative", "discourse"]),
        ("Drag performance gender theory", ["theory", "society", "culture", "performance", "stage"]),
        ("Vaudeville historical performance", ["history", "performance", "theatr", "culture", "tradition"]),
        ("Burlesque performance art", ["performance", "theatr", "culture", "stage", "history"]),
        ("Site-specific theater design", ["theatr", "space", "design", "performance", "stage"]),
        ("Broadway musical orchestration", ["broadway", "harmony", "performance", "orchestrat", "stage"]),
        ("Off-off-Broadway experimental theater", ["theatr", "broadway", "performance", "stage", "experimental"]),
        ("Children's theater pedagogy", ["theatr", "pedagog", "education", "performance", "stage"]),
        ("Mask theater traditions", ["theatr", "tradition", "culture", "performance", "stage"]),
        ("Ritual dance ethnography", ["ritual", "dance", "culture", "tradition", "anthropology"]),
        ("Flamenco performance tradition", ["dance", "tradition", "rhythm", "performance", "culture"]),
        ("Tap dance rhythm structure", ["dance", "rhythm", "structure", "motion", "performance"]),
        ("Jazz dance improvisation", ["dance", "improvis", "rhythm", "performance", "music"]),
        ("Choreographic notation Laban", ["choreograph", "notation", "motion", "dance", "system"]),
        ("Performance art conceptualism", ["performance", "concept", "art", "theory", "behavior"]),
        ("Stage acoustics and projection", ["acoust", "stage", "sound", "wave", "performance"]),
        ("Costume design silhouette", ["design", "form", "visual", "performance", "stage"]),
        ("Wig and makeup transformation", ["design", "performance", "stage", "color", "form"]),
        ("Audience interaction theater", ["theatr", "audience", "behavior", "performance", "stage"]),
        ("Verbatim documentary theater", ["theatr", "documentary", "narrative", "performance", "history"]),
        ("Ensemble physical theater", ["theatr", "motion", "ensemble", "performance", "stage"]),
        ("Puppet animation craft", ["puppet", "motion", "performance", "animation", "stage"]),
    ],
    "film_studies": [
        ("Cognitive film theory", ["cognition", "perception", "narrative", "emotion", "film"]),
        ("Digital color grading", ["color", "technology", "visual", "design", "cinema"]),
        ("Non-linear narrative editing", ["montage", "narrative", "structure", "editing", "cinema"]),
        ("Sound design in horror film", ["sound", "emotion", "design", "psychology", "cinema"]),
        ("Auteur theory and directorial style", ["theory", "narrative", "visual", "cinema", "criticism"]),
        ("Documentary ethics", ["ethics", "truth", "narrative", "society", "cinema"]),
        ("Visual effects compositing", ["computation", "visual", "design", "technology", "cinema"]),
        ("Slow cinema temporal aesthetics", ["motion", "perception", "form", "cinema", "philosophy"]),
        ("Film preservation and archiving", ["archival", "conservation", "material", "historical", "cinema"]),
        ("Semiotics of cinema", ["semantic", "meaning", "language", "cinema", "theory"]),
        ("French New Wave aesthetics", ["history", "cinema", "movie", "narrative", "criticism"]),
        ("Italian Neorealism social theory", ["theory", "society", "cinema", "narrative", "history"]),
        ("German Expressionist cinema", ["history", "cinema", "visual", "emotion", "design"]),
        ("Soviet montage theory", ["montage", "editing", "theory", "history", "cinema"]),
        ("Hollywood Golden Age genre", ["genre", "cinema", "history", "narrative", "industry"]),
        ("Film noir visual style", ["visual", "cinema", "narrative", "design", "history"]),
        ("Spaghetti Western reinvention", ["genre", "cinema", "history", "narrative", "culture"]),
        ("Hong Kong action cinema", ["cinema", "motion", "culture", "narrative", "performance"]),
        ("Bollywood musical structure", ["cinema", "music", "narrative", "culture", "rhythm"]),
        ("Anime visual storytelling", ["animation", "narrative", "visual", "culture", "cinema"]),
        ("Cinema verite documentary ethics", ["documentary", "ethics", "cinema", "truth", "narrative"]),
        ("Direct cinema observation", ["cinema", "documentary", "behavior", "observation", "narrative"]),
        ("Found footage horror tradition", ["cinema", "narrative", "tradition", "emotion", "design"]),
        ("Mockumentary parody form", ["cinema", "narrative", "documentary", "comedy", "form"]),
        ("Stop motion animation craft", ["animation", "motion", "design", "cinema", "craft"]),
        ("Computer-generated animation history", ["animation", "computation", "cinema", "history", "design"]),
        ("Visual effects digital workflow", ["computation", "visual", "design", "cinema", "workflow"]),
        ("IMAX immersive cinema", ["cinema", "perception", "sensory", "scale", "visual"]),
        ("3D stereoscopic film grammar", ["cinema", "perception", "visual", "geometric", "design"]),
        ("Virtual reality narrative form", ["narrative", "perception", "technology", "cinema", "space"]),
        ("Television aesthetics theory", ["theory", "cinema", "media", "narrative", "design"]),
        ("Streaming platform algorithm bias", ["algorithm", "data", "cinema", "media", "society"]),
        ("Fan film community production", ["cinema", "community", "culture", "society", "movie"]),
        ("Cinematic universe franchise design", ["cinema", "narrative", "design", "system", "industry"]),
        ("Film festival curation politics", ["cinema", "policy", "society", "culture", "industry"]),
        ("Independent film financing", ["cinema", "finance", "industry", "policy", "production"]),
        ("Film score composition", ["cinema", "music", "composition", "emotion", "design"]),
        ("Foley sound design craft", ["sound", "cinema", "design", "craft", "perception"]),
        ("Subtitle translation theory", ["language", "translation", "theory", "cinema", "communication"]),
        ("Restoration of silent films", ["cinema", "history", "archival", "conservation", "material"]),
        ("Censorship and film history", ["cinema", "history", "policy", "society", "rights"]),
        ("Propaganda film analysis", ["propaganda", "cinema", "society", "narrative", "history"]),
        ("War documentary ethics", ["war", "documentary", "ethics", "history", "cinema"]),
        ("Coming-of-age narrative form", ["narrative", "cinema", "psychology", "behavior", "form"]),
        ("Heroine's journey storytelling", ["narrative", "storytelling", "psychology", "mythology", "cinema"]),
    ],
    "visual_arts": [
        ("Pigment chemistry and lightfastness", ["chemistry", "material", "color", "light", "measurement"]),
        ("Perspective geometry in Renaissance painting", ["geometry", "space", "historical", "visual", "design"]),
        ("Digital generative art", ["algorithm", "computation", "pattern", "design", "visual"]),
        ("Sculpture material mechanics", ["material", "force", "form", "structure", "design"]),
        ("Color perception psychophysics", ["color", "perception", "cognition", "measurement", "visual"]),
        ("Art conservation science", ["conservation", "chemistry", "material", "measurement", "historical"]),
        ("Installation art and spatial experience", ["space", "design", "perception", "behavior", "visual"]),
        ("Mosaic tessellation mathematics", ["geometry", "pattern", "design", "material", "visual"]),
        ("Kinetic sculpture mechanics", ["motion", "mechanical", "design", "visual", "energy"]),
        ("Art market economics", ["market", "finance", "economics", "society", "visual"]),
        ("Renaissance fresco technique", ["fresco", "history", "material", "visual", "tradition"]),
        ("Oil painting medium chemistry", ["chemistry", "material", "color", "visual", "molecular"]),
        ("Watercolor pigment dispersion", ["pigment", "color", "chemistry", "material", "visual"]),
        ("Acrylic polymer paint history", ["polymer", "chemistry", "color", "history", "material"]),
        ("Egg tempera revival", ["material", "tradition", "history", "color", "visual"]),
        ("Stained glass composition", ["composition", "color", "material", "design", "tradition"]),
        ("Bronze casting metallurgy", ["material", "alloy", "form", "structure", "tradition"]),
        ("Marble sculpture technique", ["material", "form", "tradition", "structure", "visual"]),
        ("Wood carving tool tradition", ["material", "tradition", "form", "craft", "visual"]),
        ("Ceramic glaze chemistry", ["chemistry", "material", "color", "ceramic", "design"]),
        ("Raku firing aesthetics", ["thermal", "ceramic", "tradition", "material", "design"]),
        ("Calligraphy brush technique", ["language", "tradition", "design", "visual", "form"]),
        ("Woodblock printing history", ["history", "material", "visual", "tradition", "design"]),
        ("Etching plate chemistry", ["chemistry", "material", "design", "visual", "engraving"]),
        ("Lithography stone preparation", ["material", "chemistry", "visual", "design", "history"]),
        ("Screen printing pattern design", ["pattern", "design", "material", "visual", "printing"]),
        ("Photography silver halide chemistry", ["chemistry", "material", "light", "photograph", "molecular"]),
        ("Digital photography sensor design", ["sensor", "design", "light", "photograph", "technology"]),
        ("Photogrammetry 3D capture", ["geometry", "computation", "measurement", "design", "space"]),
        ("Land art environmental scale", ["nature", "scale", "design", "ecological", "visual"]),
        ("Performance art body practice", ["performance", "body", "behavior", "art", "visual"]),
        ("Video art temporal form", ["form", "design", "motion", "visual", "concept"]),
        ("Fiber arts textile composition", ["composition", "material", "pattern", "design", "tradition"]),
        ("Quilting community tradition", ["pattern", "tradition", "community", "design", "material"]),
        ("Tattoo art cultural anthropology", ["culture", "tradition", "design", "body", "anthropology"]),
        ("Graffiti urban aesthetics", ["urban", "design", "color", "visual", "society"]),
        ("Street photography ethics", ["ethics", "photograph", "society", "visual", "rights"]),
        ("Surrealist dream imagery", ["imagery", "psychology", "visual", "narrative", "history"]),
        ("Cubism multi-perspective form", ["form", "visual", "history", "perception", "design"]),
        ("Abstract expressionism gesture", ["abstract", "emotion", "form", "visual", "history"]),
        ("Color field painting perception", ["color", "perception", "visual", "form", "abstract"]),
        ("Op art visual perception", ["visual", "perception", "pattern", "design", "color"]),
        ("Pop art consumer culture", ["culture", "society", "visual", "history", "design"]),
        ("Conceptual art idea-based", ["concept", "theory", "philosophy", "visual", "art"]),
        ("Curatorial practice and display", ["design", "space", "visual", "narrative", "society"]),
    ],
    "music": [
        ("Tuning systems and temperament", ["frequency", "mathematics", "harmony", "acoustics", "sound"]),
        ("Spectral analysis of timbre", ["spectral", "frequency", "timbre", "measurement", "sound"]),
        ("Algorithmic composition", ["algorithm", "computation", "pattern", "music", "design"]),
        ("Psychoacoustics auditory perception", ["perception", "cognition", "sound", "neuroscience", "frequency"]),
        ("Music cognition and memory", ["cognition", "memory", "perception", "brain", "sound"]),
        ("Audio signal processing", ["signal", "computation", "frequency", "algorithm", "sound"]),
        ("Music therapy for trauma", ["therapy", "emotion", "trauma", "neuroscience", "sound"]),
        ("Electronic music synthesis", ["electrical", "computation", "wave", "design", "sound"]),
        ("Music and emotion neuroscience", ["emotion", "brain", "neuroscience", "cognition", "sound"]),
        ("Music information retrieval", ["data", "algorithm", "computation", "pattern", "sound"]),
        ("Microtonality and pitch space", ["frequency", "space", "harmony", "sound", "theory"]),
        ("Just intonation tuning", ["frequency", "harmony", "tradition", "sound", "mathematics"]),
        ("Equal temperament history", ["history", "harmony", "frequency", "tradition", "sound"]),
        ("Modal jazz harmony", ["harmony", "tradition", "music", "improvis", "sound"]),
        ("Bebop improvisation theory", ["theory", "improvis", "harmony", "rhythm", "music"]),
        ("Hindustani raga structure", ["structure", "tradition", "harmony", "culture", "rhythm"]),
        ("Carnatic music ornament", ["tradition", "culture", "harmony", "rhythm", "music"]),
        ("Gamelan ensemble interlocking", ["tradition", "culture", "rhythm", "ensemble", "sound"]),
        ("African polyrhythmic drumming", ["polyrhythm", "rhythm", "tradition", "culture", "sound"]),
        ("Latin clave rhythm", ["rhythm", "tradition", "culture", "sound", "pattern"]),
        ("Funk rhythmic groove analysis", ["groove", "rhythm", "music", "sound", "pattern"]),
        ("Hip-hop sampling aesthetics", ["culture", "music", "sound", "pattern", "design"]),
        ("Electronic dance music genres", ["genre", "music", "rhythm", "culture", "sound"]),
        ("Ambient music texture", ["texture", "music", "sound", "design", "perception"]),
        ("Drone music sustained pitch", ["frequency", "sound", "music", "perception", "wave"]),
        ("Computer-generated music systems", ["computation", "system", "music", "algorithm", "sound"]),
        ("Live coding performance", ["performance", "computation", "music", "improvis", "code"]),
        ("Concert hall acoustics design", ["acoust", "design", "sound", "structure", "wave"]),
        ("Recording studio engineering", ["sound", "engineering", "design", "signal", "music"]),
        ("Microphone polar pattern", ["sound", "wave", "pattern", "sensor", "design"]),
        ("Audio mastering techniques", ["sound", "signal", "design", "performance", "music"]),
        ("Vinyl record physics", ["wave", "material", "sound", "physics", "music"]),
        ("Digital audio sampling theorem", ["sampling", "frequency", "signal", "theorem", "sound"]),
        ("Perceptual audio compression", ["perception", "compression", "signal", "sound", "algorithm"]),
        ("Music streaming recommendation systems", ["algorithm", "data", "music", "system", "behavior"]),
        ("Songwriting craft analysis", ["narrative", "music", "language", "design", "structure"]),
        ("Choral conducting gesture", ["motion", "performance", "music", "ensemble", "behavior"]),
        ("Orchestral conducting tradition", ["tradition", "performance", "music", "ensemble", "orchestrat"]),
        ("Jazz improvisation pedagogy", ["improvis", "pedagog", "music", "education", "training"]),
        ("Children's music education", ["music", "education", "pedagog", "learning", "training"]),
        ("Music therapy depression treatment", ["therapy", "depression", "music", "well-being", "neural"]),
        ("Music and language acquisition", ["music", "language", "learning", "cognition", "brain"]),
        ("Voice and breath physiology", ["sound", "anatomy", "performance", "muscle", "music"]),
        ("Musical memory and dementia", ["memory", "music", "cognition", "neuroscience", "brain"]),
        ("Music and movement coupling", ["motion", "rhythm", "music", "behavior", "perception"]),
    ],
    "religion": [
        ("Comparative theology methods", ["theory", "analysis", "culture", "tradition", "doctrine"]),
        ("Buddhist meditation neuroscience", ["neuroscience", "brain", "cognition", "meditation", "spiritual"]),
        ("Dead Sea Scrolls scholarship", ["archival", "historical", "language", "sacred", "manuscript"]),
        ("Liberation theology and social justice", ["justice", "ethics", "society", "doctrine", "power"]),
        ("Cognitive science of religion", ["cognition", "evolution", "behavior", "brain", "belief"]),
        ("Church-state separation law", ["legal", "governance", "rights", "doctrine", "society"]),
        ("Confucian ethics and virtue", ["ethics", "virtue", "tradition", "culture", "moral"]),
        ("Ritual symbolism and semiotics", ["ritual", "semantic", "culture", "tradition", "behavior"]),
        ("Nature religion and animism", ["nature", "spiritual", "tradition", "ecosystem", "ritual"]),
        ("Apocalyptic literature analysis", ["narrative", "literary", "sacred", "historical", "doctrine"]),
        ("Sufism mystical tradition", ["mysticism", "tradition", "spiritual", "culture", "doctrine"]),
        ("Zen Buddhism meditation practice", ["meditation", "spiritual", "tradition", "behavior", "philosophy"]),
        ("Tibetan Buddhist ritual", ["ritual", "tradition", "spiritual", "culture", "doctrine"]),
        ("Hindu temple architecture", ["temple", "tradition", "structure", "design", "sacred"]),
        ("Shinto kami nature reverence", ["spiritual", "nature", "tradition", "culture", "ritual"]),
        ("Daoist alchemy tradition", ["tradition", "culture", "history", "doctrine", "spiritual"]),
        ("Indigenous shamanism studies", ["indigenous", "tradition", "spiritual", "ritual", "culture"]),
        ("Quakerism silent worship", ["worship", "tradition", "spiritual", "community", "doctrine"]),
        ("Pentecostal spiritual experience", ["spiritual", "tradition", "behavior", "community", "doctrine"]),
        ("Reformation theology history", ["history", "doctrine", "tradition", "ethics", "religion"]),
        ("Counter-Reformation art history", ["history", "tradition", "visual", "doctrine", "culture"]),
        ("Crusades religious history", ["history", "war", "religion", "tradition", "culture"]),
        ("Inquisition legal history", ["history", "legal", "doctrine", "justice", "religion"]),
        ("Reformation Bible translation", ["language", "translation", "history", "doctrine", "sacred"]),
        ("Hadith scholarship method", ["language", "tradition", "doctrine", "manuscript", "sacred"]),
        ("Talmudic interpretation methodology", ["language", "tradition", "discourse", "doctrine", "manuscript"]),
        ("Liturgical chant musicology", ["liturgy", "music", "tradition", "sound", "ritual"]),
        ("Iconography Eastern Orthodox", ["visual", "tradition", "sacred", "history", "doctrine"]),
        ("Pilgrimage geography study", ["pilgrimage", "tradition", "spiritual", "behavior", "culture"]),
        ("New religious movements sociology", ["society", "behavior", "culture", "tradition", "movement"]),
        ("Fundamentalism comparative analysis", ["doctrine", "behavior", "culture", "society", "tradition"]),
        ("Secularization theory", ["theory", "society", "culture", "behavior", "doctrine"]),
        ("Religious experience neuroscience", ["neuroscience", "brain", "spiritual", "behavior", "cognition"]),
        ("Religion and capitalism", ["religion", "economics", "society", "ethics", "behavior"]),
        ("Religious freedom law", ["legal", "rights", "freedom", "doctrine", "policy"]),
        ("Interfaith dialogue ethics", ["ethics", "dialogue", "doctrine", "discourse", "community"]),
        ("Eco-theology environmental ethics", ["ethics", "ecosystem", "doctrine", "nature", "philosophy"]),
        ("Religion and gender studies", ["religion", "society", "tradition", "rights", "culture"]),
    ],
    "law": [
        ("Constitutional originalism debate", ["constitution", "interpretation", "historical", "governance", "rights"]),
        ("International humanitarian law", ["human rights", "justice", "governance", "ethics", "international"]),
        ("Algorithmic bias and legal liability", ["algorithm", "computation", "ethics", "legal", "rights"]),
        ("Antitrust economics and market power", ["market", "competition", "economics", "governance", "legal"]),
        ("Environmental law and regulation", ["ecosystem", "policy", "governance", "sustainability", "legal"]),
        ("Criminal sentencing algorithms", ["algorithm", "justice", "computation", "ethics", "legal"]),
        ("Privacy law and data protection", ["data", "rights", "technology", "legal", "governance"]),
        ("Legal reasoning and argumentation", ["logic", "reasoning", "discourse", "legal", "cognition"]),
        ("Space law and orbital governance", ["space", "governance", "legal", "orbit", "international"]),
        ("Restorative justice programs", ["justice", "community", "ethics", "behavior", "legal"]),
        ("Common law evolution", ["legal", "history", "tradition", "jurisprudence", "court"]),
        ("Civil law tradition history", ["legal", "tradition", "history", "jurisprudence", "court"]),
        ("Sharia law jurisprudence", ["legal", "jurisprudence", "tradition", "doctrine", "religion"]),
        ("Talmudic legal reasoning", ["legal", "discourse", "tradition", "religion", "doctrine"]),
        ("Indigenous legal traditions", ["indigenous", "tradition", "legal", "rights", "culture"]),
        ("Comparative constitutional law", ["constitution", "legal", "governance", "history", "rights"]),
        ("International criminal court", ["court", "justice", "international", "rights", "legal"]),
        ("Refugee law international", ["legal", "rights", "international", "policy", "migration"]),
        ("Maritime law admiralty", ["legal", "trade", "international", "ocean", "history"]),
        ("Cyber law jurisdiction", ["legal", "technology", "rights", "governance", "data"]),
        ("Intellectual property patent", ["legal", "rights", "innovation", "policy", "design"]),
        ("Trademark law and branding", ["legal", "rights", "market", "design", "policy"]),
        ("Copyright fair use doctrine", ["legal", "rights", "doctrine", "policy", "culture"]),
        ("Tort liability and negligence", ["liability", "legal", "ethics", "rights", "policy"]),
        ("Contract formation rules", ["contract", "legal", "rights", "policy", "discourse"]),
        ("Corporate governance law", ["governance", "legal", "policy", "ethics", "economics"]),
        ("Tax law and policy", ["taxation", "legal", "policy", "economics", "governance"]),
        ("Family law adoption", ["family", "legal", "rights", "society", "policy"]),
        ("Divorce law settlement", ["family", "legal", "rights", "society", "policy"]),
        ("Estate planning trust law", ["legal", "policy", "asset", "rights", "family"]),
        ("Bankruptcy law restructure", ["legal", "policy", "economics", "rights", "finance"]),
        ("Labor law collective bargaining", ["labor", "legal", "rights", "policy", "society"]),
        ("Employment discrimination law", ["legal", "rights", "labor", "society", "ethics"]),
        ("Disability rights law", ["legal", "rights", "policy", "society", "ethics"]),
        ("LGBTQ rights jurisprudence", ["legal", "rights", "jurisprudence", "society", "ethics"]),
        ("Immigration law policy", ["legal", "policy", "rights", "migration", "governance"]),
        ("Death penalty jurisprudence", ["legal", "justice", "ethics", "rights", "policy"]),
        ("Juvenile justice law", ["legal", "justice", "rights", "ethics", "policy"]),
    ],
}
