// Part 1: physics, biology, computer_science, philosophy, economics, music, medicine
// 7 categories × 25 = 175 concepts
// Requires constants and Concept struct from corpus.rs

fn build_corpus_part1() -> Vec<Concept> { vec![
// ── PHYSICS (25) ──
Concept{label:"Newtonian mechanics",category:"physics",features:vec![(FORCE,1.0),(ENERGY,0.7),(MATH,0.6),(SPACE,0.5),(MOTION,0.6)]},
Concept{label:"Quantum field theory",category:"physics",features:vec![(QUANTUM,1.0),(ENERGY,0.8),(MATH,0.9),(WAVE,0.6)]},
Concept{label:"General relativity",category:"physics",features:vec![(SPACE,1.0),(ENERGY,0.7),(MATH,0.9),(FORCE,0.6)]},
Concept{label:"Thermodynamics",category:"physics",features:vec![(ENERGY,1.0),(ENTROPY,0.9),(CHEMISTRY,0.3),(SYSTEMS,0.4)]},
Concept{label:"Electromagnetism",category:"physics",features:vec![(FORCE,0.8),(ENERGY,0.8),(WAVE,0.9),(MATH,0.5)]},
Concept{label:"Statistical mechanics",category:"physics",features:vec![(STATISTICS,0.8),(ENERGY,0.7),(ENTROPY,0.8),(MATH,0.7)]},
Concept{label:"Optics",category:"physics",features:vec![(WAVE,1.0),(ENERGY,0.5),(SPACE,0.4),(PATTERN,0.3),(VISUAL,0.4)]},
Concept{label:"Particle physics",category:"physics",features:vec![(QUANTUM,0.9),(ENERGY,0.9),(FORCE,0.7),(MATH,0.6)]},
Concept{label:"Cosmology",category:"physics",features:vec![(SPACE,0.9),(ENERGY,0.6),(MATH,0.5),(ENTROPY,0.4)]},
Concept{label:"Fluid dynamics",category:"physics",features:vec![(FORCE,0.7),(ENERGY,0.6),(MATH,0.7),(WAVE,0.5),(MOTION,0.7)]},
Concept{label:"Acoustics",category:"physics",features:vec![(WAVE,0.9),(SOUND,0.8),(ENERGY,0.4),(PATTERN,0.5),(MATH,0.3)]},
Concept{label:"Information theory (physics)",category:"physics",features:vec![(ENTROPY,0.9),(INFORMATION,0.8),(MATH,0.7),(COMPUTATION,0.4)]},
Concept{label:"Biophysics",category:"physics",features:vec![(ENERGY,0.6),(LIFE,0.5),(CHEMISTRY,0.5),(FORCE,0.4),(SYSTEMS,0.3)]},
Concept{label:"Nuclear physics",category:"physics",features:vec![(QUANTUM,0.8),(ENERGY,1.0),(FORCE,0.8)]},
Concept{label:"Condensed matter",category:"physics",features:vec![(QUANTUM,0.6),(STRUCTURE,0.7),(ENERGY,0.5),(MATH,0.5),(MATERIAL,0.5)]},
Concept{label:"Plasma physics",category:"physics",features:vec![(ENERGY,0.9),(FORCE,0.6),(WAVE,0.5),(SPACE,0.3),(MOTION,0.4)]},
Concept{label:"Laser physics",category:"physics",features:vec![(WAVE,0.9),(ENERGY,0.7),(QUANTUM,0.6),(MEASUREMENT,0.5)]},
Concept{label:"Nonlinear dynamics",category:"physics",features:vec![(MATH,0.8),(SYSTEMS,0.7),(PATTERN,0.7),(MOTION,0.6),(ENTROPY,0.4)]},
Concept{label:"Solid state physics",category:"physics",features:vec![(QUANTUM,0.6),(STRUCTURE,0.8),(ENERGY,0.5),(MATERIAL,0.7)]},
Concept{label:"Cryogenics",category:"physics",features:vec![(ENERGY,0.7),(ENTROPY,0.6),(QUANTUM,0.5),(MEASUREMENT,0.5)]},
Concept{label:"Photonics",category:"physics",features:vec![(WAVE,0.9),(ENERGY,0.6),(INFORMATION,0.5),(QUANTUM,0.4)]},
Concept{label:"Classical field theory",category:"physics",features:vec![(MATH,0.9),(FORCE,0.8),(SPACE,0.6),(WAVE,0.5)]},
Concept{label:"Atomic physics",category:"physics",features:vec![(QUANTUM,0.8),(ENERGY,0.7),(WAVE,0.5),(MEASUREMENT,0.4)]},
Concept{label:"Rheology",category:"physics",features:vec![(FORCE,0.7),(MATERIAL,0.8),(MOTION,0.6),(MATH,0.4)]},
Concept{label:"Quantum information",category:"physics",features:vec![(QUANTUM,0.9),(INFORMATION,0.9),(COMPUTATION,0.6),(MATH,0.7),(ENTROPY,0.5)]},
// ── BIOLOGY (25) ──
Concept{label:"Evolution by natural selection",category:"biology",features:vec![(EVOLUTION,1.0),(LIFE,0.9),(GENETICS,0.7),(NATURE,0.6)]},
Concept{label:"Molecular biology",category:"biology",features:vec![(LIFE,0.9),(CHEMISTRY,0.8),(GENETICS,0.7),(STRUCTURE,0.5)]},
Concept{label:"Ecology",category:"biology",features:vec![(LIFE,0.8),(NATURE,1.0),(SYSTEMS,0.7),(ECOLOGY,0.9),(EVOLUTION,0.4)]},
Concept{label:"Genetics",category:"biology",features:vec![(GENETICS,1.0),(LIFE,0.8),(INFORMATION,0.5),(CHEMISTRY,0.4)]},
Concept{label:"Cell biology",category:"biology",features:vec![(LIFE,1.0),(CHEMISTRY,0.6),(SYSTEMS,0.5),(STRUCTURE,0.5)]},
Concept{label:"Bioinformatics",category:"biology",features:vec![(LIFE,0.5),(COMPUTATION,0.7),(GENETICS,0.6),(INFORMATION,0.6),(STATISTICS,0.5)]},
Concept{label:"Immunology",category:"biology",features:vec![(LIFE,0.8),(CHEMISTRY,0.5),(SYSTEMS,0.6),(EVOLUTION,0.3)]},
Concept{label:"Botany",category:"biology",features:vec![(LIFE,0.8),(NATURE,0.9),(CHEMISTRY,0.3),(EVOLUTION,0.3),(ECOLOGY,0.5)]},
Concept{label:"Marine biology",category:"biology",features:vec![(LIFE,0.8),(NATURE,0.8),(EVOLUTION,0.4),(ECOLOGY,0.7)]},
Concept{label:"Microbiology",category:"biology",features:vec![(LIFE,0.9),(CHEMISTRY,0.5),(EVOLUTION,0.5),(GENETICS,0.4)]},
Concept{label:"Developmental biology",category:"biology",features:vec![(LIFE,0.9),(GENETICS,0.6),(SYSTEMS,0.5),(STRUCTURE,0.4)]},
Concept{label:"Evolutionary psychology",category:"biology",features:vec![(EVOLUTION,0.7),(MIND,0.6),(BEHAVIOR,0.6),(COGNITION,0.5)]},
Concept{label:"Biostatistics",category:"biology",features:vec![(LIFE,0.5),(STATISTICS,0.8),(MATH,0.5),(GENETICS,0.3)]},
Concept{label:"Taxonomy",category:"biology",features:vec![(LIFE,0.7),(EVOLUTION,0.6),(STRUCTURE,0.6),(NATURE,0.5)]},
Concept{label:"Zoology",category:"biology",features:vec![(LIFE,0.9),(EVOLUTION,0.6),(NATURE,0.7),(BEHAVIOR,0.4)]},
Concept{label:"Parasitology",category:"biology",features:vec![(LIFE,0.8),(EVOLUTION,0.5),(ECOLOGY,0.5),(SYSTEMS,0.3)]},
Concept{label:"Mycology",category:"biology",features:vec![(LIFE,0.8),(CHEMISTRY,0.5),(NATURE,0.6),(ECOLOGY,0.4)]},
Concept{label:"Virology",category:"biology",features:vec![(LIFE,0.8),(GENETICS,0.6),(EVOLUTION,0.6),(CHEMISTRY,0.4)]},
Concept{label:"Conservation biology",category:"biology",features:vec![(LIFE,0.7),(ECOLOGY,0.9),(NATURE,0.8),(ETHICS,0.4)]},
Concept{label:"Population genetics",category:"biology",features:vec![(GENETICS,0.9),(EVOLUTION,0.8),(STATISTICS,0.7),(MATH,0.5)]},
Concept{label:"Ethology",category:"biology",features:vec![(BEHAVIOR,0.9),(LIFE,0.7),(EVOLUTION,0.5),(COGNITION,0.4)]},
Concept{label:"Proteomics",category:"biology",features:vec![(LIFE,0.7),(CHEMISTRY,0.7),(INFORMATION,0.6),(COMPUTATION,0.4)]},
Concept{label:"Systems biology",category:"biology",features:vec![(LIFE,0.7),(SYSTEMS,0.9),(COMPUTATION,0.5),(NETWORK,0.6)]},
Concept{label:"Entomology",category:"biology",features:vec![(LIFE,0.8),(NATURE,0.7),(EVOLUTION,0.5),(ECOLOGY,0.5)]},
Concept{label:"Epigenetics",category:"biology",features:vec![(GENETICS,0.8),(LIFE,0.7),(CHEMISTRY,0.5),(EVOLUTION,0.4),(INFORMATION,0.4)]},
// ── COMPUTER SCIENCE (25) ──
Concept{label:"Algorithm design",category:"computer_science",features:vec![(COMPUTATION,0.9),(LOGIC,0.8),(MATH,0.7),(OPTIMIZATION,0.6)]},
Concept{label:"Machine learning",category:"computer_science",features:vec![(COMPUTATION,0.8),(STATISTICS,0.7),(PATTERN,0.8),(OPTIMIZATION,0.7)]},
Concept{label:"Database systems",category:"computer_science",features:vec![(COMPUTATION,0.7),(INFORMATION,0.8),(STRUCTURE,0.7),(SYSTEMS,0.6)]},
Concept{label:"Networking",category:"computer_science",features:vec![(COMPUTATION,0.6),(NETWORK,0.9),(SYSTEMS,0.7),(INFORMATION,0.5)]},
Concept{label:"Cryptography",category:"computer_science",features:vec![(COMPUTATION,0.8),(MATH,0.9),(INFORMATION,0.7),(LOGIC,0.5)]},
Concept{label:"Operating systems",category:"computer_science",features:vec![(COMPUTATION,0.8),(SYSTEMS,0.9),(STRUCTURE,0.5),(LOGIC,0.4)]},
Concept{label:"Artificial intelligence",category:"computer_science",features:vec![(COMPUTATION,0.8),(COGNITION,0.6),(LOGIC,0.6),(PATTERN,0.5),(MIND,0.3)]},
Concept{label:"Computational complexity",category:"computer_science",features:vec![(COMPUTATION,0.9),(MATH,0.9),(LOGIC,0.8)]},
Concept{label:"Computer graphics",category:"computer_science",features:vec![(COMPUTATION,0.7),(MATH,0.5),(SPACE,0.5),(VISUAL,0.7),(PATTERN,0.4)]},
Concept{label:"Natural language processing",category:"computer_science",features:vec![(COMPUTATION,0.7),(LANGUAGE,0.8),(PATTERN,0.6),(COGNITION,0.4),(STATISTICS,0.5)]},
Concept{label:"Algorithmic trading",category:"computer_science",features:vec![(COMPUTATION,0.6),(MARKETS,0.7),(OPTIMIZATION,0.7),(STATISTICS,0.5)]},
Concept{label:"Computational biology",category:"computer_science",features:vec![(COMPUTATION,0.7),(LIFE,0.4),(GENETICS,0.4),(STATISTICS,0.5),(PATTERN,0.4)]},
Concept{label:"Formal verification",category:"computer_science",features:vec![(COMPUTATION,0.7),(LOGIC,1.0),(MATH,0.8)]},
Concept{label:"Information retrieval",category:"computer_science",features:vec![(COMPUTATION,0.6),(INFORMATION,0.9),(LANGUAGE,0.4),(PATTERN,0.5)]},
Concept{label:"Distributed systems",category:"computer_science",features:vec![(COMPUTATION,0.7),(SYSTEMS,0.8),(NETWORK,0.7),(LOGIC,0.3)]},
Concept{label:"Human-computer interaction",category:"computer_science",features:vec![(COMPUTATION,0.5),(COGNITION,0.7),(VISUAL,0.5),(BEHAVIOR,0.5),(PERFORMANCE,0.3)]},
Concept{label:"Compiler design",category:"computer_science",features:vec![(COMPUTATION,0.9),(LANGUAGE,0.6),(LOGIC,0.7),(STRUCTURE,0.6)]},
Concept{label:"Computer vision",category:"computer_science",features:vec![(COMPUTATION,0.8),(VISUAL,0.9),(PATTERN,0.8),(MATH,0.4)]},
Concept{label:"Parallel computing",category:"computer_science",features:vec![(COMPUTATION,0.9),(SYSTEMS,0.7),(OPTIMIZATION,0.6),(MATH,0.3)]},
Concept{label:"Cybersecurity",category:"computer_science",features:vec![(COMPUTATION,0.7),(INFORMATION,0.7),(LOGIC,0.6),(NETWORK,0.6),(ETHICS,0.3)]},
Concept{label:"Quantum computing",category:"computer_science",features:vec![(COMPUTATION,0.8),(QUANTUM,0.9),(MATH,0.7),(INFORMATION,0.6)]},
Concept{label:"Software engineering",category:"computer_science",features:vec![(COMPUTATION,0.8),(STRUCTURE,0.8),(LOGIC,0.6),(SYSTEMS,0.6)]},
Concept{label:"Reinforcement learning",category:"computer_science",features:vec![(COMPUTATION,0.7),(OPTIMIZATION,0.8),(BEHAVIOR,0.5),(PATTERN,0.5)]},
Concept{label:"Computational geometry",category:"computer_science",features:vec![(COMPUTATION,0.7),(MATH,0.8),(SPACE,0.7),(STRUCTURE,0.5)]},
Concept{label:"Robotics (CS)",category:"computer_science",features:vec![(COMPUTATION,0.7),(MOTION,0.7),(SYSTEMS,0.6),(FORCE,0.4),(COGNITION,0.3)]},
// ── PHILOSOPHY (25) ──
Concept{label:"Formal logic",category:"philosophy",features:vec![(LOGIC,1.0),(MATH,0.7),(LANGUAGE,0.4),(STRUCTURE,0.4)]},
Concept{label:"Ethics",category:"philosophy",features:vec![(ETHICS,1.0),(BEHAVIOR,0.6),(MIND,0.4)]},
Concept{label:"Philosophy of mind",category:"philosophy",features:vec![(MIND,1.0),(COGNITION,0.7),(METAPHYSICS,0.6),(LANGUAGE,0.3)]},
Concept{label:"Epistemology",category:"philosophy",features:vec![(MIND,0.7),(LOGIC,0.6),(METAPHYSICS,0.5),(COGNITION,0.5)]},
Concept{label:"Metaphysics",category:"philosophy",features:vec![(METAPHYSICS,1.0),(MIND,0.5),(SPACE,0.3),(STRUCTURE,0.3)]},
Concept{label:"Philosophy of language",category:"philosophy",features:vec![(LANGUAGE,0.8),(LOGIC,0.6),(MIND,0.5),(STRUCTURE,0.4)]},
Concept{label:"Political philosophy",category:"philosophy",features:vec![(ETHICS,0.7),(BEHAVIOR,0.6),(SYSTEMS,0.5),(GOVERNANCE,0.5)]},
Concept{label:"Bioethics",category:"philosophy",features:vec![(ETHICS,0.9),(LIFE,0.5),(DIAGNOSTICS,0.3),(MIND,0.3)]},
Concept{label:"Game theory (philosophy)",category:"philosophy",features:vec![(LOGIC,0.7),(BEHAVIOR,0.7),(MATH,0.6),(OPTIMIZATION,0.5),(MARKETS,0.3)]},
Concept{label:"Aesthetics",category:"philosophy",features:vec![(MIND,0.5),(EMOTION,0.7),(VISUAL,0.4),(ETHICS,0.2)]},
Concept{label:"Philosophy of science",category:"philosophy",features:vec![(LOGIC,0.6),(METAPHYSICS,0.5),(MIND,0.4),(STRUCTURE,0.4),(MEASUREMENT,0.3)]},
Concept{label:"Phenomenology",category:"philosophy",features:vec![(MIND,0.8),(METAPHYSICS,0.7),(COGNITION,0.5)]},
Concept{label:"Existentialism",category:"philosophy",features:vec![(MIND,0.7),(EMOTION,0.6),(METAPHYSICS,0.7),(ETHICS,0.4)]},
Concept{label:"Philosophy of mathematics",category:"philosophy",features:vec![(LOGIC,0.8),(MATH,0.8),(METAPHYSICS,0.6),(STRUCTURE,0.5)]},
Concept{label:"Virtue ethics",category:"philosophy",features:vec![(ETHICS,0.9),(BEHAVIOR,0.7),(EMOTION,0.4),(MIND,0.3)]},
Concept{label:"Social contract theory",category:"philosophy",features:vec![(ETHICS,0.7),(BEHAVIOR,0.7),(GOVERNANCE,0.6),(LOGIC,0.4)]},
Concept{label:"Utilitarianism",category:"philosophy",features:vec![(ETHICS,0.9),(OPTIMIZATION,0.6),(BEHAVIOR,0.5),(MATH,0.3)]},
Concept{label:"Philosophy of technology",category:"philosophy",features:vec![(MIND,0.5),(COMPUTATION,0.4),(ETHICS,0.5),(METAPHYSICS,0.4)]},
Concept{label:"Free will debate",category:"philosophy",features:vec![(MIND,0.8),(METAPHYSICS,0.8),(BEHAVIOR,0.5),(COGNITION,0.4)]},
Concept{label:"Hermeneutics",category:"philosophy",features:vec![(LANGUAGE,0.7),(MIND,0.6),(NARRATIVE,0.5),(METAPHYSICS,0.5)]},
Concept{label:"Modal logic",category:"philosophy",features:vec![(LOGIC,0.9),(MATH,0.7),(METAPHYSICS,0.5),(STRUCTURE,0.4)]},
Concept{label:"Environmental ethics",category:"philosophy",features:vec![(ETHICS,0.9),(NATURE,0.7),(ECOLOGY,0.5),(BEHAVIOR,0.3)]},
Concept{label:"Philosophy of art",category:"philosophy",features:vec![(MIND,0.5),(EMOTION,0.7),(METAPHYSICS,0.5),(VISUAL,0.4),(PERFORMANCE,0.3)]},
Concept{label:"Pragmatism",category:"philosophy",features:vec![(MIND,0.6),(BEHAVIOR,0.6),(LOGIC,0.5),(COGNITION,0.4)]},
Concept{label:"Consciousness studies",category:"philosophy",features:vec![(MIND,0.9),(COGNITION,0.8),(METAPHYSICS,0.6),(LIFE,0.3)]},
// ── ECONOMICS (25) ──
Concept{label:"Microeconomics",category:"economics",features:vec![(MARKETS,0.9),(OPTIMIZATION,0.8),(BEHAVIOR,0.6),(MATH,0.5)]},
Concept{label:"Macroeconomics",category:"economics",features:vec![(MARKETS,0.8),(SYSTEMS,0.7),(STATISTICS,0.5),(BEHAVIOR,0.4)]},
Concept{label:"Behavioral economics",category:"economics",features:vec![(BEHAVIOR,0.9),(MARKETS,0.6),(COGNITION,0.5),(MIND,0.3)]},
Concept{label:"Econometrics",category:"economics",features:vec![(STATISTICS,0.9),(MATH,0.7),(MARKETS,0.6),(COMPUTATION,0.3)]},
Concept{label:"Game theory (economics)",category:"economics",features:vec![(MATH,0.7),(OPTIMIZATION,0.8),(BEHAVIOR,0.6),(LOGIC,0.4),(MARKETS,0.5)]},
Concept{label:"Financial engineering",category:"economics",features:vec![(MARKETS,0.8),(MATH,0.7),(OPTIMIZATION,0.6),(COMPUTATION,0.4)]},
Concept{label:"Development economics",category:"economics",features:vec![(MARKETS,0.6),(SYSTEMS,0.5),(BEHAVIOR,0.5),(ETHICS,0.3),(GOVERNANCE,0.4)]},
Concept{label:"Labor economics",category:"economics",features:vec![(MARKETS,0.7),(BEHAVIOR,0.6),(SYSTEMS,0.4),(STATISTICS,0.3)]},
Concept{label:"Network economics",category:"economics",features:vec![(MARKETS,0.6),(NETWORK,0.7),(SYSTEMS,0.6),(OPTIMIZATION,0.4)]},
Concept{label:"Environmental economics",category:"economics",features:vec![(MARKETS,0.5),(NATURE,0.5),(ECOLOGY,0.5),(ETHICS,0.3)]},
Concept{label:"Public choice theory",category:"economics",features:vec![(BEHAVIOR,0.7),(MARKETS,0.5),(LOGIC,0.4),(GOVERNANCE,0.5)]},
Concept{label:"Auction theory",category:"economics",features:vec![(MATH,0.6),(OPTIMIZATION,0.7),(MARKETS,0.7),(BEHAVIOR,0.4)]},
Concept{label:"Monetary economics",category:"economics",features:vec![(MARKETS,0.8),(SYSTEMS,0.6),(GOVERNANCE,0.5),(STATISTICS,0.4)]},
Concept{label:"International trade",category:"economics",features:vec![(MARKETS,0.8),(NETWORK,0.6),(SYSTEMS,0.5),(GOVERNANCE,0.3)]},
Concept{label:"Health economics",category:"economics",features:vec![(MARKETS,0.6),(LIFE,0.5),(DIAGNOSTICS,0.4),(STATISTICS,0.5)]},
Concept{label:"Agricultural economics",category:"economics",features:vec![(MARKETS,0.7),(NATURE,0.5),(ECOLOGY,0.4),(SYSTEMS,0.4)]},
Concept{label:"Industrial organization",category:"economics",features:vec![(MARKETS,0.8),(SYSTEMS,0.6),(OPTIMIZATION,0.5),(STRUCTURE,0.4)]},
Concept{label:"Welfare economics",category:"economics",features:vec![(MARKETS,0.6),(ETHICS,0.6),(OPTIMIZATION,0.6),(GOVERNANCE,0.4)]},
Concept{label:"Resource economics",category:"economics",features:vec![(MARKETS,0.6),(NATURE,0.6),(ECOLOGY,0.5),(OPTIMIZATION,0.5)]},
Concept{label:"Urban economics",category:"economics",features:vec![(MARKETS,0.6),(STRUCTURE,0.5),(SYSTEMS,0.5),(NETWORK,0.4)]},
Concept{label:"Information economics",category:"economics",features:vec![(MARKETS,0.6),(INFORMATION,0.8),(BEHAVIOR,0.5),(OPTIMIZATION,0.4)]},
Concept{label:"Risk management",category:"economics",features:vec![(MARKETS,0.7),(STATISTICS,0.7),(MATH,0.5),(OPTIMIZATION,0.5)]},
Concept{label:"Experimental economics",category:"economics",features:vec![(BEHAVIOR,0.7),(MARKETS,0.5),(STATISTICS,0.6),(MEASUREMENT,0.4)]},
Concept{label:"Mechanism design",category:"economics",features:vec![(MATH,0.7),(OPTIMIZATION,0.8),(LOGIC,0.6),(MARKETS,0.5)]},
Concept{label:"Economic history",category:"economics",features:vec![(MARKETS,0.7),(BEHAVIOR,0.5),(SYSTEMS,0.5),(EVOLUTION,0.4),(NARRATIVE,0.3)]},
// ── MUSIC (25) ──
Concept{label:"Harmonic theory",category:"music",features:vec![(SOUND,0.8),(MATH,0.7),(PATTERN,0.8),(WAVE,0.5)]},
Concept{label:"Orchestration",category:"music",features:vec![(SOUND,0.9),(PERFORMANCE,0.7),(EMOTION,0.5),(SYSTEMS,0.3)]},
Concept{label:"Rhythm and meter",category:"music",features:vec![(SOUND,0.7),(PATTERN,1.0),(MATH,0.4),(PERFORMANCE,0.4)]},
Concept{label:"Musical acoustics",category:"music",features:vec![(SOUND,0.9),(WAVE,0.8),(ENERGY,0.4),(MATH,0.3),(PATTERN,0.3)]},
Concept{label:"Music cognition",category:"music",features:vec![(SOUND,0.5),(COGNITION,0.7),(EMOTION,0.6),(PATTERN,0.5),(MIND,0.3)]},
Concept{label:"Composition",category:"music",features:vec![(SOUND,0.7),(EMOTION,0.7),(PATTERN,0.6),(STRUCTURE,0.5)]},
Concept{label:"Ethnomusicology",category:"music",features:vec![(SOUND,0.6),(LANGUAGE,0.5),(BEHAVIOR,0.4),(PATTERN,0.4),(COGNITION,0.3)]},
Concept{label:"Music theory",category:"music",features:vec![(SOUND,0.7),(MATH,0.6),(PATTERN,0.7),(STRUCTURE,0.5)]},
Concept{label:"Performance practice",category:"music",features:vec![(PERFORMANCE,1.0),(SOUND,0.7),(EMOTION,0.6),(MOTION,0.3)]},
Concept{label:"Digital audio",category:"music",features:vec![(SOUND,0.7),(COMPUTATION,0.6),(WAVE,0.5),(INFORMATION,0.4)]},
Concept{label:"Music therapy",category:"music",features:vec![(SOUND,0.5),(EMOTION,0.8),(MIND,0.4),(DIAGNOSTICS,0.2),(COGNITION,0.3)]},
Concept{label:"Counterpoint",category:"music",features:vec![(SOUND,0.6),(PATTERN,0.7),(MATH,0.5),(STRUCTURE,0.6)]},
Concept{label:"Choral conducting",category:"music",features:vec![(PERFORMANCE,0.9),(SOUND,0.7),(EMOTION,0.6),(SYSTEMS,0.3)]},
Concept{label:"Film scoring",category:"music",features:vec![(SOUND,0.7),(EMOTION,0.8),(NARRATIVE,0.6),(VISUAL,0.3)]},
Concept{label:"Sound design",category:"music",features:vec![(SOUND,0.9),(COMPUTATION,0.5),(WAVE,0.6),(EMOTION,0.4)]},
Concept{label:"Musical notation",category:"music",features:vec![(SOUND,0.5),(LANGUAGE,0.6),(PATTERN,0.7),(STRUCTURE,0.5),(INFORMATION,0.3)]},
Concept{label:"Tuning systems",category:"music",features:vec![(SOUND,0.7),(MATH,0.8),(WAVE,0.6),(MEASUREMENT,0.4)]},
Concept{label:"Music production",category:"music",features:vec![(SOUND,0.8),(COMPUTATION,0.5),(PERFORMANCE,0.5),(SYSTEMS,0.3)]},
Concept{label:"Improvisation",category:"music",features:vec![(PERFORMANCE,0.8),(EMOTION,0.7),(COGNITION,0.6),(PATTERN,0.5)]},
Concept{label:"Opera studies",category:"music",features:vec![(PERFORMANCE,0.8),(SOUND,0.7),(LANGUAGE,0.6),(EMOTION,0.7),(NARRATIVE,0.5)]},
Concept{label:"Musical form analysis",category:"music",features:vec![(PATTERN,0.8),(STRUCTURE,0.7),(MATH,0.4),(SOUND,0.5)]},
Concept{label:"Early music practice",category:"music",features:vec![(PERFORMANCE,0.7),(SOUND,0.6),(EVOLUTION,0.4),(PATTERN,0.4)]},
Concept{label:"Music information retrieval",category:"music",features:vec![(SOUND,0.6),(COMPUTATION,0.7),(INFORMATION,0.7),(PATTERN,0.6)]},
Concept{label:"Songwriting",category:"music",features:vec![(SOUND,0.6),(LANGUAGE,0.7),(EMOTION,0.8),(NARRATIVE,0.5)]},
Concept{label:"World music studies",category:"music",features:vec![(SOUND,0.6),(BEHAVIOR,0.5),(LANGUAGE,0.4),(EVOLUTION,0.4),(PATTERN,0.5)]},
// ── MEDICINE (25) ──
Concept{label:"Clinical diagnostics",category:"medicine",features:vec![(DIAGNOSTICS,1.0),(LIFE,0.6),(STATISTICS,0.5),(SYSTEMS,0.3)]},
Concept{label:"Pharmacology",category:"medicine",features:vec![(CHEMISTRY,0.9),(LIFE,0.7),(DIAGNOSTICS,0.4),(SYSTEMS,0.3)]},
Concept{label:"Epidemiology",category:"medicine",features:vec![(STATISTICS,0.9),(LIFE,0.6),(SYSTEMS,0.6),(NETWORK,0.4)]},
Concept{label:"Surgery",category:"medicine",features:vec![(LIFE,0.7),(DIAGNOSTICS,0.6),(FORCE,0.3),(PERFORMANCE,0.4)]},
Concept{label:"Psychiatry",category:"medicine",features:vec![(MIND,0.7),(LIFE,0.6),(DIAGNOSTICS,0.5),(BEHAVIOR,0.5),(CHEMISTRY,0.3)]},
Concept{label:"Radiology",category:"medicine",features:vec![(DIAGNOSTICS,0.8),(WAVE,0.5),(ENERGY,0.3),(VISUAL,0.5),(COMPUTATION,0.3)]},
Concept{label:"Pathology",category:"medicine",features:vec![(LIFE,0.7),(CHEMISTRY,0.5),(DIAGNOSTICS,0.7),(STRUCTURE,0.3)]},
Concept{label:"Genomic medicine",category:"medicine",features:vec![(GENETICS,0.7),(LIFE,0.6),(DIAGNOSTICS,0.5),(INFORMATION,0.4),(COMPUTATION,0.3)]},
Concept{label:"Medical imaging AI",category:"medicine",features:vec![(DIAGNOSTICS,0.6),(COMPUTATION,0.7),(PATTERN,0.6),(VISUAL,0.5),(STATISTICS,0.4)]},
Concept{label:"Public health",category:"medicine",features:vec![(LIFE,0.5),(STATISTICS,0.6),(SYSTEMS,0.6),(BEHAVIOR,0.4),(ETHICS,0.3)]},
Concept{label:"Neurology",category:"medicine",features:vec![(LIFE,0.6),(MIND,0.5),(DIAGNOSTICS,0.6),(COGNITION,0.4),(NETWORK,0.3)]},
Concept{label:"Immunotherapy",category:"medicine",features:vec![(LIFE,0.7),(CHEMISTRY,0.5),(SYSTEMS,0.5),(DIAGNOSTICS,0.3)]},
Concept{label:"Cardiology",category:"medicine",features:vec![(LIFE,0.7),(DIAGNOSTICS,0.7),(SYSTEMS,0.4),(MEASUREMENT,0.4)]},
Concept{label:"Oncology",category:"medicine",features:vec![(LIFE,0.8),(CHEMISTRY,0.5),(GENETICS,0.5),(DIAGNOSTICS,0.6)]},
Concept{label:"Dermatology",category:"medicine",features:vec![(LIFE,0.6),(DIAGNOSTICS,0.7),(VISUAL,0.5),(PATTERN,0.4)]},
Concept{label:"Anesthesiology",category:"medicine",features:vec![(LIFE,0.6),(CHEMISTRY,0.6),(SYSTEMS,0.4),(MEASUREMENT,0.5)]},
Concept{label:"Emergency medicine",category:"medicine",features:vec![(LIFE,0.8),(DIAGNOSTICS,0.7),(SYSTEMS,0.5),(PERFORMANCE,0.4)]},
Concept{label:"Pediatrics",category:"medicine",features:vec![(LIFE,0.8),(DIAGNOSTICS,0.5),(BEHAVIOR,0.3),(EVOLUTION,0.2)]},
Concept{label:"Geriatrics",category:"medicine",features:vec![(LIFE,0.7),(DIAGNOSTICS,0.5),(SYSTEMS,0.4),(EVOLUTION,0.3)]},
Concept{label:"Rehabilitation medicine",category:"medicine",features:vec![(LIFE,0.6),(MOTION,0.6),(DIAGNOSTICS,0.5),(PERFORMANCE,0.4)]},
Concept{label:"Telemedicine",category:"medicine",features:vec![(DIAGNOSTICS,0.5),(COMPUTATION,0.6),(NETWORK,0.6),(INFORMATION,0.5)]},
Concept{label:"Evidence-based medicine",category:"medicine",features:vec![(STATISTICS,0.8),(DIAGNOSTICS,0.6),(LOGIC,0.5),(MEASUREMENT,0.5)]},
Concept{label:"Sports medicine",category:"medicine",features:vec![(LIFE,0.6),(MOTION,0.7),(FORCE,0.4),(DIAGNOSTICS,0.5)]},
Concept{label:"Toxicology",category:"medicine",features:vec![(CHEMISTRY,0.8),(LIFE,0.6),(DIAGNOSTICS,0.5),(MEASUREMENT,0.4)]},
Concept{label:"Medical ethics",category:"medicine",features:vec![(ETHICS,0.9),(LIFE,0.5),(MIND,0.4),(GOVERNANCE,0.3)]},
]}
