//! JSON loader for the extended corpus.
//!
//! The extended corpus JSON is embedded at compile time via
//! [`include_str!`] and parsed once at the call site of
//! [`load_extended_corpus`]. The `serde_json` parse is fast (~10 MB/s on
//! a single thread for this shape), so callers don't need to cache the
//! result for a single embedding pass — but see the memory warning on
//! [`load_extended_corpus`] before calling repeatedly.

use serde::Deserialize;

use crate::concept::Concept;

const EXTENDED_JSON: &str = include_str!("../data/extended_corpus.json");

#[derive(Deserialize)]
struct RawConcept {
    label: String,
    category: String,
    features: Vec<[f64; 2]>,
}

#[derive(Deserialize)]
struct RawCorpus {
    concepts: Vec<RawConcept>,
}

/// Load the extended corpus from the embedded JSON.
///
/// The data file ships ~5,000+ concepts sourced from the OpenAlex Topics
/// taxonomy (CC0) plus hand-authored gap-fill for thin categories. Each
/// returned [`Concept`] carries 4–8 sparse feature axes with weights in
/// `[0.2, 1.0]`, matching the format of the hand-crafted [`build_corpus`].
///
/// # Memory warning
///
/// Labels and category names are leaked to `&'static str` via
/// `Box::leak` so they fit [`Concept`]'s signature. Each call leaks
/// `2 * concepts.len()` strings (roughly 5,000 labels + 5,000 category
/// references, ~250 KB total). **Leaks DO accumulate across calls** —
/// every invocation leaks a fresh set. Call at most once per process in
/// production code. Tests and examples are fine: the per-process total
/// stays in the low MB even across a full test suite, but a long-lived
/// service that re-loads on every request would grow without bound.
///
/// # Panics
///
/// Panics if the embedded JSON fails to deserialize. This is a logic
/// bug — the data file is generated by `tools/generate_extended.py` and
/// validated before commit; a parse failure means the schema or build
/// pipeline is broken.
///
/// [`build_corpus`]: crate::build_corpus
pub fn load_extended_corpus() -> Vec<Concept> {
    let raw: RawCorpus = serde_json::from_str(EXTENDED_JSON)
        .expect("extended_corpus.json is malformed — regenerate via tools/generate_extended.py");

    raw.concepts
        .into_iter()
        .map(|rc| Concept {
            label: leak_str(rc.label),
            category: leak_str(rc.category),
            features: rc
                .features
                .into_iter()
                .map(|pair| (pair[0] as usize, pair[1]))
                .collect(),
        })
        .collect()
}

/// Leak an owned String to `&'static str`. Called twice per concept
/// (label + category) at corpus-load time.
fn leak_str(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}
